### ISSUE TITLE
Spaces between firstname and surname affect result

### ISSUE THREAD

**Issue by mstephens1** [jmfrank63/foc_dataset#1]
`create_dataset.py "Firstname Surname"` 

returns 

> ['woul', 'expe', 'find', 'lect', 'note', 'text', 'exam', 'want', 'know', 'abou', 'your', 'proj', 'they', 'have', 'many']

but 

`create_dataset.py "FirstnameSurname"` 

returns

> ['engl', 'exam', 'cann', 'expe', 'look', 'kind', 'repo', 'that', 'badl', 'writ', 'stud', 'vary', 'ofte', 'they', 'need']

**Comment by jmfrank63** [comment]
Merged Exclude spaces from encode_name
